# Generated by Django 3.1.7 on 2021-04-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=100)),
                ('ename', models.CharField(max_length=100)),
                ('eaddress', models.CharField(max_length=100)),
                ('egender', models.CharField(max_length=100)),
                ('ephoneno', models.CharField(max_length=100)),
            ],
        ),
    ]
